name: 'Setup Jikkou Wrapper'

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  jikkou-wrapper:
    name: 'Jikkou Versions'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        jikkou-versions: [latest]

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Setup Jikkou - ${{ matrix['jikkou-versions'] }}
        uses: ./
        with:
          jikkou_version: ${{ matrix['jikkou-versions'] }}
          jikkou_wrapper: true

      - name: Validate Jikkou Version - ${{ matrix['jikkou-versions'] }}
        id: version
        run: jikkou -V | grep 'Jikkou version'

      - name: 'Output stdout'
        run: echo "${{ steps.version.outputs.stdout }}"

      - name: 'Output stderr'
        run: echo "${{ steps.version.outputs.stderr }}"

      - name: 'Output exitcode'
        run: echo "${{ steps.version.outputs.exitcode }}"
        
